import {expirePendingHistoryDeletes,HISTORY_MATCH_TIMEOUT_MS} from '../server/management.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createStore,hash,secret} from '../server/store.mjs';
import {createApp} from '../server/app.mjs';
test('guarded history deletion, offline acknowledgments, phone changes and block conflicts',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'relay-management-')),store=createStore(dir);
 const user=store.createUser('fixture','Fixture','synthetic-password'),other=store.createUser('other','Other','synthetic-password');
 const token=secret(),session=secret(),csrf=secret(),origin='http://localhost:49760';
 store.run('INSERT INTO devices(id,user_id,token,data) VALUES(?,?,?,?)','fixture-device',user,hash(token),store.seal({}));
 store.run('INSERT INTO sessions(token,user_id,csrf,expires) VALUES(?,?,?,?)',hash(session),user,csrf,Date.now()+60000);
 const app=createApp(store,{origin}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(async()=>{app.locals.voice.close();await new Promise(r=>server.close(r));store.db.close();rmSync(dir,{recursive:true,force:true});});
 async function request(path,body,method=body?'POST':'GET',device=false){const r=await fetch(`http://127.0.0.1:${server.address().port}/api${path}`,{method,headers:{Origin:origin,'Content-Type':'application/json',...(device?{Authorization:'Bearer '+token}:{Cookie:'relay_session='+session,'X-CSRF-Token':csrf})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:r.status===204?{}:await r.json()};}
 const row={id:'smsdb-910-0',type:'sms',number:'+12025550199',originalNumber:'+12025550199',sim:0,timestamp:1000,sentTimestamp:0,direction:'incoming',status:'received',text:'Synthetic deletion fixture',read:false};
 const history=records=>request('/device/history',{records},'POST',true);
 const sync=(missing=[],results=[])=>request('/device/history/sync',{missing,results},'POST',true);
 assert.equal((await history([row])).status,200);
 const id=store.state(user).messages[0].id;
 assert.equal((await request('/messages/'+id,null,'DELETE')).status,204);
 assert.equal(store.state(user).messages.length,0);
 assert.deepEqual(store.open(store.get('SELECT data FROM messages WHERE id=?',id).data),{deleted:true});
 let action=(await sync()).data.actions[0];assert.equal(action.source,row.id);assert.equal(action.action,'delete');assert.equal(action.text,undefined);assert.equal(action.textHash.length,64);
 await history([row]);assert.equal(store.state(user).messages.length,0,'offline reimport cannot resurrect');
 await sync([],[{id:action.id,ok:false,error:'permission'}]);assert.equal(store.state(user).historySync.failed,1);
 await sync([],[{id:action.id,ok:true}]);assert.equal(store.state(user).historySync.pending,0);
 assert.equal((await request('/messages/'+id,null,'DELETE')).status,204,'repeat deletion');
 await history([{...row,id:'smsdb-911-0',timestamp:2000}]);
 await sync(['smsdb-911-0']);assert.equal(store.state(user).messages.length,0,'phone deletion reaches website');
 const c=store.conversation(other,row.number,1),foreign=secret();store.run('INSERT INTO messages VALUES(?,?,?,?,?,?)',foreign,other,c.id,store.seal({text:'Other private fixture'}),1000,0);
 assert.equal((await request('/messages/'+foreign,null,'DELETE')).status,404);assert.equal(store.state(other).messages.length,1);
 const block=(number,blocked)=>request('/blocks',{number,blocked});
 const blocks=(changes=[],acknowledgments=[],imported=[])=>request('/device/blocks/sync',{changes,acknowledgments,imported},'POST',true);
 assert.equal((await block('+1 (202) 555-0199',true)).status,204);let b=(await blocks()).data.blocks[0];assert.equal(b.number,row.number);
 await blocks([],[{id:b.id,version:b.version}]);assert.equal(store.state(user).blocks[0].phoneSynced,true);
 await blocks([{id:b.id,version:b.version,blocked:false}]);assert.equal(store.state(user).blocks[0].blocked,false);
 await block(row.number,true);await blocks([{id:b.id,version:b.version,blocked:false}]);assert.equal(store.state(user).blocks[0].blocked,true,'stale phone change cannot override newer website edit');
 await block(row.number,false);await blocks([],[],[row.number]);assert.equal(store.state(user).blocks[0].blocked,false,'stale import cannot resurrect blocked number');
 assert.equal(store.state(other).blocks.length,0);
 await history([{...row,id:'smsdb-912-0',timestamp:3000},{...row,id:'smsdb-913-0',timestamp:4000}]);
 assert.equal((await request('/messages',null,'DELETE')).status,204);assert.equal(store.state(user).messages.length,0);assert.equal((await sync()).data.actions.length,2);
 await history([{...row,id:'smsdb-912-3000',timestamp:3000}]);assert.equal(store.state(user).messages.length,0,'identity upgrade retains tombstone');
 await history([{...row,id:'smsdb-912-5000',timestamp:5000}]);assert.equal(store.state(user).messages.length,1,'reused Android row ID does not hide new SMS');
 // An unlinked live SMS can be deleted before its provider record arrives.
 const late=store.conversation(user,row.number,1),lateId=secret();
 store.run('INSERT INTO messages VALUES(?,?,?,?,?,?)',lateId,user,late.id,store.seal({text:'Deferred fixture',sim:1,direction:'incoming',status:'received'}),9000,1);
 assert.equal((await request('/messages/'+lateId,null,'DELETE')).status,204);
 assert.equal((await request('/messages/'+lateId,null,'DELETE')).status,204);
 assert.ok(!store.state(user).messages.some(m=>m.id===lateId));
 assert.equal(store.all('SELECT * FROM pending_history_deletes WHERE target_id=?',lateId).length,1);
 assert.equal(store.state(user).historySync.awaitingHistory,1);
 await history([{...row,id:'smsdb-950-9001',timestamp:9001,sim:1,text:'Deferred fixture'}]);
 assert.equal(store.all('SELECT * FROM pending_history_deletes WHERE target_id=?',lateId).length,1,'similar message must not be deleted');
 await history([{...row,id:'smsdb-951-9000',timestamp:9000,sim:1,text:'Deferred fixture'}]);
 assert.equal(store.all('SELECT * FROM pending_history_deletes WHERE target_id=?',lateId).length,0);
 assert.equal(store.state(user).historySync.awaitingHistory,0);
 assert.deepEqual(store.open(store.get('SELECT data FROM messages WHERE id=?',lateId).data),{deleted:true});
 const deferred=(await sync()).data.actions.filter(a=>a.source==='smsdb-951-9000');
 assert.equal(deferred.length,1);
 await history([{...row,id:'smsdb-951-9000',timestamp:9000,sim:1,text:'Deferred fixture'}]);
 assert.equal((await sync()).data.actions.filter(a=>a.source==='smsdb-951-9000').length,1,'reimport must not duplicate deletion');
 assert.ok(!store.state(user).messages.some(m=>m.id===lateId));

 // A timed-out unmatched request must never delete a late phone record.
 const timeoutId=secret(),timeoutDate=16000;
 store.run('INSERT INTO messages VALUES(?,?,?,?,?,?)',timeoutId,user,late.id,store.seal({text:'Timeout fixture',sim:1,direction:'incoming',status:'received'}),timeoutDate,0);
 await request('/messages/'+timeoutId,null,'DELETE');
 const started=store.get('SELECT created_at FROM pending_history_deletes WHERE target_id=?',timeoutId).created_at;
 assert.equal(store.transaction(()=>expirePendingHistoryDeletes(store,user,started+HISTORY_MATCH_TIMEOUT_MS-1)),0);
 assert.equal(store.transaction(()=>expirePendingHistoryDeletes(store,other,started+HISTORY_MATCH_TIMEOUT_MS)),0,'account scope');
 store.run('UPDATE pending_history_deletes SET created_at=? WHERE target_id=?',Date.now()-HISTORY_MATCH_TIMEOUT_MS-1,timeoutId);
 await history([{...row,id:'smsdb-970-16000',timestamp:timeoutDate,sim:1,text:'Timeout fixture'}]);
 assert.equal(store.state(user).historySync.awaitingHistory,0);
 const phoneCopy=store.state(user).messages.find(m=>m.text==='Timeout fixture');
 assert.ok(phoneCopy,'actual phone record is shown after timeout');
 assert.notEqual(phoneCopy.id,timeoutId,'unverified old panel copy stays hidden');
 assert.equal((await sync()).data.actions.some(a=>a.source==='smsdb-970-16000'),false,'late match cannot revive canceled deletion');
 assert.deepEqual(store.open(store.get('SELECT data FROM messages WHERE id=?',timeoutId).data),{deleted:true});
 await history([{...row,id:'smsdb-970-16000',timestamp:timeoutDate,sim:1,text:'Timeout fixture'}]);
 assert.equal(store.state(user).messages.filter(m=>m.text==='Timeout fixture').length,1);
 // Call history uses the same deadline, including when no browser is open.
 const timeoutCall=secret();store.run('INSERT INTO calls VALUES(?,?,?,?)',timeoutCall,user,store.seal({number:row.number,sim:1,direction:'incoming',duration:2}),17000);
 await request('/calls/'+timeoutCall,null,'DELETE');
 const callStart=store.get('SELECT created_at FROM pending_history_deletes WHERE target_id=?',timeoutCall).created_at;
 assert.equal(store.transaction(()=>expirePendingHistoryDeletes(store,user,callStart+HISTORY_MATCH_TIMEOUT_MS)),1,'expires at five minutes');
 await history([{id:'call-971-17000',type:'call',number:row.number,originalNumber:row.number,sim:1,timestamp:17000,sentTimestamp:0,direction:'incoming',duration:2}]);
 assert.ok(store.state(user).calls.some(c=>c.id!==timeoutCall));
 assert.equal((await sync()).data.actions.some(a=>a.source==='call-971-17000'),false);
 const alerts=[];let refreshes=0;
 app.locals.voice.notifySms=async(user,sms)=>alerts.push({user,...sms});
 app.locals.voice.dataChanged=()=>refreshes++;
 const liveRow={...row,id:'smsdb-960-12000',timestamp:12000,live:true,text:'Live fixture'};
 await history([liveRow]);await history([liveRow]);
 await history([{...row,id:'smsdb-961-13000',timestamp:13000,text:'Old fixture'}]);
 await history([{...row,id:'smsdb-962-14000',timestamp:14000,live:true,direction:'outgoing',status:'sent'}]);
 assert.equal(alerts.length,1,'only new live incoming history triggers push');
 assert.equal(alerts[0].user,user);assert.ok(alerts[0].conversationId);
 assert.equal(alerts[0].text,liveRow.text);assert.equal(alerts[0].number,liveRow.number);
 assert.equal(refreshes,3,'imports signal immediate browser refresh, retries do not');
 const subscription={endpoint:'https://fcm.googleapis.com/fake-synthetic',keys:{p256dh:'a'.repeat(90),auth:'b'.repeat(22)}};
 assert.equal((await request('/voice/push',subscription)).status,204);
 assert.equal((await request('/voice/push/status',{endpoint:subscription.endpoint})).data.enabled,true);
 assert.equal((await request('/voice/push',{endpoint:subscription.endpoint},'DELETE')).status,204);
 assert.equal((await request('/voice/push/status',{endpoint:subscription.endpoint})).data.enabled,false);

});

test('legacy pending deletion schema migrates without restarting its deadline',()=>{
 const dir=mkdtempSync(join(tmpdir(),'relay-deletion-migration-'));
 let store=createStore(dir);
 try {
  store.db.exec('DROP TABLE pending_history_deletes; CREATE TABLE pending_history_deletes(user_id TEXT NOT NULL,kind TEXT NOT NULL,target_id TEXT NOT NULL,PRIMARY KEY(user_id,kind,target_id))');
  store.run('INSERT INTO pending_history_deletes VALUES(?,?,?)','legacy-user','sms','legacy-message');
  store.db.close();store=createStore(dir);
  assert.equal(store.get('SELECT created_at FROM pending_history_deletes').created_at,0);
  store.state('legacy-user');
  assert.equal(store.all('SELECT * FROM pending_history_deletes').length,0);
 } finally {store.db.close();rmSync(dir,{recursive:true,force:true});}
});
